### ISSUE TITLE
El Capitan and Pineapple Nano

### ISSUE THREAD

**Issue by confuded** [TGYK/OSXwp5#1]
I've skimmed through [this post](https://forums.hak5.org/index.php?/topic/33801-mac-osx-internet-sharing-with-wifi-pineapple-howto/) at Hak5.

I am running OS X El Capitan and just bought the Pineapple Nano. It is connected to my MBP early 2013 through its network USB port. The connection to pineapple is configured to have a static ip of 172.16.42.42. The device is at 172.16.42.1. I've run the script and set Pineapple's default route to 172.16.42.42. It did not work - i.e. the pineapple did not have an internet connection, while the laptop did.
The device I am trying to share the connection from is the built-in Wi-Fi card.
I've run the script and it didn't work. I disabled ICS and ran the script with the -n option and got the following:

```
NAT file created
NAT file edited
ICS started
IP on en0 set to 172.16.42.42
Ethernet is not a recognized network service.
** Error: The parameters were not valid.
Set Primary DNS to 8.8.8.8 Alternate to 8.8.4.4
Set: Entry, ":Subnets:0:dhcp_domain_name_server:0", Does Not Exist
Set: Entry, ":Subnets:0:dhcp_router", Does Not Exist
Set: Entry, ":Subnets:0:net_range:0", Does Not Exist
Rewritten bootpd file for DHCP
Copied completed config files
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Reloaded bootpd file for DHCP
```

Version:

```
System version code: 10112
Script version: 1.7
```

Yes, I am running as root (via sudo).

~confuded

**Comment by buley** [comment]
@confuded the deal from what I can tell is that these scripts relied on managing a process (`bootpd`) that no longer exists on El Cap.

**Comment by TGYK** [comment]
Sorry for the super late reply!
I haven't taken a look at this code in quite some time, admittedly, it fell by the wayside once I got bored with my Pineapple. I never got around to doing any sort of testing on El Capitan, so sorry for that.

ICS on mac is weird. Like really weird. From my research, there's no real easy way to change it's ip addressing range, or to enable/disable it, making these scripts very ramshackle and 'hacked' together. And on top of that, the components which I use to accomplish this seem to change drastically with each new update. There isn't a ton of documentation of the behind-the-scenes workings of OS X ICS, so the chances of me coming back and updating this project are slim. Sorry!
